### PR TITLE
MaterializedPathSegment

### PR DESCRIPTION
**Pull request by density215**
- A Proposal for a materialized Path Segment (MaterializedPathSegment), that holds its ASNs as a vec, so it can be passed around independently and can be modified in place.
- Modification methods on AS_PATH (related to MaterializedPathSegment).
- Remove old stuff

shouldn't probably not be merged like this (Martin wants to convert the whole AsPath & AsPAthBuilder to hold Octs always, instead of a intermediate &[Asn]).

### CODE REVIEW

**Comment by partim** [comment]
I indeed propose to change the type to be `AsPath<Octs>` and hold the wire-format of an AS path. The `AsPathBuilder<_>` would then hold an octets builder and would provide methods to manipulate that builder.

The only (?) problem is that prepending a single ASN – the most commonly performed path manipulation – is really quite expensive. As a workaround, we could have `AsPath<Octs>` keep an extra `Option<Asn>` which can hold one ASN to prepend when composing.

**Comment by density215** [comment]
The plot thickens, I've added two traits (`ScalarValue` and `VectorValue`), as well as the `AttrChangeSet`, that I think should be the primitives to modify BGP Update messages.

**Comment by partim** [comment]
I’m still not entirely convince this is general purpose enough to live in routecore rather than Rotonda.

**Comment by density215** [comment]
There should be a way to modify and create new BGP Updates in routecore in any case, no? This is a proposal to do that.

It's in nobody's interest if Rotonda has a method that completely diverges from the one offered in routecore. 

So this is just a proposal, the final way of doing this can be different, and I'll adapt Rotonda to that.

**Pull request closed without merging**
